### ISSUE TITLE
PyPy Support

### ISSUE THREAD

**Issue by KumaTea** [KumaTea/pytorch-aarch64#3]
## PyPy Support Status

![status](https://img.shields.io/badge/build-%E2%9C%94%203179%20%7C%20%E2%9C%98%202%20%7C%20%3F%20108-red)

Wheels of [**PyPy**](https://www.pypy.org/) versions of PyTorch could not be released yet, because PyPy does not support all C functions that PyTorch implemented.

In this thread I will report all errors that occurred during building using PyPy.

**Comment by KumaTea** [comment]
```patch
diff --git a/torch/csrc/utils/python_arg_parser.h b/torch/csrc/utils/python_arg_parser.h
index 0454e7e2af..27f97b6308 100644
--- a/torch/csrc/utils/python_arg_parser.h
+++ b/torch/csrc/utils/python_arg_parser.h
@@ -697,7 +697,7 @@ static bool _is_basic_python_type(PyTypeObject *tp)
     tp == Py_TYPE(Py_Ellipsis) ||
     tp == Py_TYPE(Py_NotImplemented) ||

-    PyModule_Check(tp) ||
+    /* PyModule_Check(tp) || */
     /* sentinel to swallow trailing || */
     false
   );
```

**Comment by KumaTea** [comment]
### `Exceptions.cpp.o`

* Version: 1.7.1
* Source: `torch/csrc/Exceptions.cpp`

```log
cmake --build . --target install --config Release -- -j 1
[1/109] Building CXX object caffe2/torch/CMakeFiles/torch_python.dir/csrc/Exceptions.cpp.o
FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/Exceptions.cpp.o
/usr/bin/c++  -DFMT_HEADER_ONLY=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTHP_BUILD_MAIN_LIB -DUSE_C10D -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DUSE_NUMPY -DUSE_RPC -DUSE_TENSORPIPE -D_FILE_OFFSET_BITS=64 -Dtorch_python_EXPORTS -Iaten/src -I../aten/src -I. -I../ -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -I../torch/.. -I../torch/../aten/src -I../torch/../aten/src/TH -Icaffe2/aten/src -Ithird_party -I../torch/../third_party/valgrind-headers -I../torch/../third_party/gloo -I../torch/../third_party/onnx -I../torch/csrc -I../torch/csrc/api/include -I../torch/lib -I../torch/lib/libshm -I../torch/csrc/api -I../c10/.. -I../torch/lib/libshm/../../../torch/lib -I../third_party/fmt/include -I../third_party/tensorpipe -Ithird_party/tensorpipe -I../third_party/tensorpipe/third_party/libnop/include -I../torch/lib/c10d/.. -I../torch/lib/c10d/../../.. -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem ../third_party/protobuf/src -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party/XNNPACK/include -isystem ../cmake/../third_party/eigen -isystem /opt/pypy/include -isystem /opt/pypy/site-packages/numpy/core/include -isystem ../cmake/../third_party/pybind11/include -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -Wno-stringop-overflow -O3 -DNDEBUG -DNDEBUG -fPIC   -DCAFFE2_USE_GLOO -D__NEON__ -DUSE_GCC_GET_CPUID -DTH_HAVE_THREAD -fno-strict-aliasing -Wno-write-strings -Wno-strict-aliasing -pthread -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unknown-pragmas -std=gnu++14 -MD -MT caffe2/torch/CMakeFiles/torch_python.dir/csrc/Exceptions.cpp.o -MF caffe2/torch/CMakeFiles/torch_python.dir/csrc/Exceptions.cpp.o.d -o caffe2/torch/CMakeFiles/torch_python.dir/csrc/Exceptions.cpp.o -c ../torch/csrc/Exceptions.cpp
../torch/csrc/Exceptions.cpp: In destructor ‘virtual torch::PyWarningHandler::~PyWarningHandler()’:
../torch/csrc/Exceptions.cpp:199:18: error: ‘PyErr_WarnExplicit’ was not declared in this scope
         result = PyErr_WarnExplicit(
                  ^~~~~~~~~~~~~~~~~~
../torch/csrc/Exceptions.cpp:199:18: note: suggested alternative: ‘PyErr_WarnEx’
         result = PyErr_WarnExplicit(
                  ^~~~~~~~~~~~~~~~~~
                  PyErr_WarnEx
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 760, in <module>
    build_deps()
  File "setup.py", line 315, in build_deps
    cmake=cmake)
  File "/root/build/pypy37/torch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/root/build/pypy37/torch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/root/build/pypy37/torch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/opt/pypy/lib-python/3/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '1']' returned non-zero exit status 1.
```

**Comment by KumaTea** [comment]
### `python_tracer.cpp`

* Version: 1.11.0
* Source: `torch/csrc/jit/python/python_tracer.cpp`
* Error: `‘PyFrameObject’ {aka ‘struct _frame’} has no member named ‘f_lasti’`
* Similar issues:
  * [python/pytorch#51074](https://github.com/pytorch/pytorch/issues/51074)
* Error logs:

```log
kuma@pi /m/u/p/p/c/p/p/w/torch (main)> pypy setup.py build        (/mnt/usb/pytorch/conda/pypy38)
Building wheel torch-1.11.0
-- Building version 1.11.0
cmake --build . --target install --config Release
[3/115] Building CXX object caffe2/torch/CMakeF..._python.dir/csrc/jit/python/python_tracer.cpp.o
FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/python/python_tracer.cpp.o
/usr/bin/c++ -DAT_PER_OPERATOR_HEADERS -DFMT_HEADER_ONLY=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTHP_BUILD_MAIN_LIB -DUSE_C10D -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DUSE_NUMPY -DUSE_RPC -DUSE_TENSORPIPE -DUSE_VALGRIND -D_FILE_OFFSET_BITS=64 -Dtorch_python_EXPORTS -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/onnx -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party/onnx -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/foxi -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party/foxi -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/.. -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../aten/src/TH -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/caffe2/aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/valgrind-headers -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/gloo -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/onnx -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/flatbuffers/include -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/api/include -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/lib -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/lib/libshm -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/distributed -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/api -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/c10/.. -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/lib/libshm/../../../torch/lib -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/fmt/include -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party/gloo -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/cmake/../third_party/gloo -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/protobuf/src -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/gemmlowp -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/neon2sse -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/XNNPACK/include -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/cmake/../third_party/eigen -isystem /mnt/usb/pytorch/conda/pypy38/include/pypy3.8 -isystem /mnt/usb/pytorch/conda/pypy38/lib/pypy3.8/site-packages/numpy/core/include -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/cmake/../third_party/pybind11/include -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -O3 -DNDEBUG -DNDEBUG -fPIC -DCAFFE2_USE_GLOO -D__NEON__ -DTH_HAVE_THREAD -Wno-unused-variable -fno-strict-aliasing -Wno-write-strings -Wno-strict-aliasing -pthread -std=gnu++14 -MD -MT caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/python/python_tracer.cpp.o -MF caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/python/python_tracer.cpp.o.d -o caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/python/python_tracer.cpp.o -c /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/python/python_tracer.cpp
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/python/python_tracer.cpp: In function ‘std::vector<torch::jit::StackEntry> torch::jit::tracer::_pythonCallstack()’:
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/python/python_tracer.cpp:33:58: error: ‘PyFrameObject’ {aka ‘struct _frame’} has no member named ‘f_lasti’
   33 |     size_t line = PyCode_Addr2Line(frame->f_code, frame->f_lasti);
      |                                                          ^~~~~~~
[6/115] Building CXX object caffe2/torch/CMakeF...n.dir/csrc/jit/tensorexpr/tensorexpr_init.cpp.o
FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/tensorexpr/tensorexpr_init.cpp.o
/usr/bin/c++ -DAT_PER_OPERATOR_HEADERS -DFMT_HEADER_ONLY=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTHP_BUILD_MAIN_LIB -DUSE_C10D -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DUSE_NUMPY -DUSE_RPC -DUSE_TENSORPIPE -DUSE_VALGRIND -D_FILE_OFFSET_BITS=64 -Dtorch_python_EXPORTS -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/onnx -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party/onnx -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/foxi -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party/foxi -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/.. -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../aten/src/TH -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/caffe2/aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/valgrind-headers -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/gloo -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/onnx -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/flatbuffers/include -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/api/include -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/lib -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/lib/libshm -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/distributed -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/api -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/c10/.. -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/lib/libshm/../../../torch/lib -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/fmt/include -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party/gloo -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/cmake/../third_party/gloo -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/protobuf/src -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/gemmlowp -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/neon2sse -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/XNNPACK/include -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/cmake/../third_party/eigen -isystem /mnt/usb/pytorch/conda/pypy38/include/pypy3.8 -isystem /mnt/usb/pytorch/conda/pypy38/lib/pypy3.8/site-packages/numpy/core/include -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/cmake/../third_party/pybind11/include -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -O3 -DNDEBUG -DNDEBUG -fPIC -DCAFFE2_USE_GLOO -D__NEON__ -DTH_HAVE_THREAD -Wno-unused-variable -fno-strict-aliasing -Wno-write-strings -Wno-strict-aliasing -pthread -std=gnu++14 -MD -MT caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/tensorexpr/tensorexpr_init.cpp.o -MF caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/tensorexpr/tensorexpr_init.cpp.o.d -o caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/tensorexpr/tensorexpr_init.cpp.o -c /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/tensorexpr/tensorexpr_init.cpp
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/tensorexpr/tensorexpr_init.cpp: In lambda function:
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/tensorexpr/tensorexpr_init.cpp:781:30: error: cannot bind non-const lvalue reference of type ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>&’ to an rvalue of type ‘pybind11::detail::generic_iterator<pybind11::detail::iterator_policies::sequence_slow_readwrite>::reference’ {aka ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>’}
  781 |             for (auto& obj : inputs) {
      |                              ^~~~~~
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/tensorexpr/tensorexpr_init.cpp: In lambda function:
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/tensorexpr/tensorexpr_init.cpp:798:30: error: cannot bind non-const lvalue reference of type ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>&’ to an rvalue of type ‘pybind11::detail::generic_iterator<pybind11::detail::iterator_policies::sequence_slow_readwrite>::reference’ {aka ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>’}
  798 |             for (auto& obj : inputs) {
      |                              ^~~~~~
[7/115] Building CXX object caffe2/torch/CMakeF...ch_python.dir/csrc/jit/python/script_init.cpp.o
FAILED: caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/python/script_init.cpp.o
/usr/bin/c++ -DAT_PER_OPERATOR_HEADERS -DFMT_HEADER_ONLY=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTHP_BUILD_MAIN_LIB -DUSE_C10D -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DUSE_NUMPY -DUSE_RPC -DUSE_TENSORPIPE -DUSE_VALGRIND -D_FILE_OFFSET_BITS=64 -Dtorch_python_EXPORTS -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/onnx -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party/onnx -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/foxi -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party/foxi -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/.. -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../aten/src/TH -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/caffe2/aten/src -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/valgrind-headers -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/gloo -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/onnx -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/../third_party/flatbuffers/include -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/api/include -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/lib -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/lib/libshm -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/distributed -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/api -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/c10/.. -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/lib/libshm/../../../torch/lib -I/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/fmt/include -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/build/third_party/gloo -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/cmake/../third_party/gloo -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/protobuf/src -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/gemmlowp -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/neon2sse -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/third_party/XNNPACK/include -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/cmake/../third_party/eigen -isystem /mnt/usb/pytorch/conda/pypy38/include/pypy3.8 -isystem /mnt/usb/pytorch/conda/pypy38/lib/pypy3.8/site-packages/numpy/core/include -isystem /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/cmake/../third_party/pybind11/include -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow -O3 -DNDEBUG -DNDEBUG -fPIC -DCAFFE2_USE_GLOO -D__NEON__ -DTH_HAVE_THREAD -Wno-unused-variable -fno-strict-aliasing -Wno-write-strings -Wno-strict-aliasing -pthread -std=gnu++14 -MD -MT caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/python/script_init.cpp.o -MF caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/python/script_init.cpp.o.d -o caffe2/torch/CMakeFiles/torch_python.dir/csrc/jit/python/script_init.cpp.o -c /mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/python/script_init.cpp
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/python/script_init.cpp: In lambda function:
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/python/script_init.cpp:1296:32: error: cannot bind non-const lvalue reference of type ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>&’ to an rvalue of type ‘pybind11::detail::generic_iterator<pybind11::detail::iterator_policies::sequence_slow_readwrite>::reference’ {aka ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>’}
 1296 |             for (auto& input : input_tuple) {
      |                                ^~~~~~~~~~~
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/python/script_init.cpp: In lambda function:
/mnt/usb/pytorch/pytorch-aarch64/conda/pp38/pytorch/work/torch/torch/csrc/jit/python/script_init.cpp:1307:32: error: cannot bind non-const lvalue reference of type ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>&’ to an rvalue of type ‘pybind11::detail::generic_iterator<pybind11::detail::iterator_policies::sequence_slow_readwrite>::reference’ {aka ‘pybind11::detail::accessor<pybind11::detail::accessor_policies::sequence_item>’}
 1307 |             for (auto& input : input_tuple) {
      |                                ^~~~~~~~~~~
[8/115] Building CXX object caffe2/torch/CMakeF...ython.dir/csrc/utils/throughput_benchmark.cpp.o
ninja: build stopped: subcommand failed.
kuma@pi /m/u/p/p/c/p/p/w/torch (main) [1]>                        (/mnt/usb/pytorch/conda/pypy38) 
```
