### ISSUE TITLE
OSError: torchaudio/_torchaudio.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

### ISSUE THREAD

**Issue by discort** [KumaTea/pytorch-aarch64#5]
## Steps to reproduce:
- install pytorch1.8 for jetson from official [source](https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available/72048)
```
wget https://nvidia.box.com/shared/static/p57jwntv436lfrd78inwl7iml6p13fzh.whl -O torch-1.8.0-cp36-cp36m-linux_aarch64.whl
pip install numpy torch-1.8.0-cp36-cp36m-linux_aarch64.whl
```
- Checking:
```
>>> import torch; torch.__version__
'1.8.0'
```
- Installing torchaudio
```
pip install torchaudio -f https://github.com/KumaTea/pytorch-aarch64/releases/download/v1.8.0/torchaudio-0.8.0-cp36-cp36m-linux_aarch64.whl
Collecting torchaudio
  Downloading https://github.com/KumaTea/pytorch-aarch64/releases/download/v1.8.0/torchaudio-0.8.0-cp36-cp36m-linux_aarch64.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 283kB/s
Requirement already satisfied: torch in ./.env/lib/python3.6/site-packages (from torchaudio)
Requirement already satisfied: numpy in ./.env/lib/python3.6/site-packages (from torch->torchaudio)
Requirement already satisfied: typing-extensions in ./.env/lib/python3.6/site-packages (from torch->torchaudio)
Requirement already satisfied: dataclasses; python_version < "3.7" in ./.env/lib/python3.6/site-packages (from torch->torchaudio)
Installing collected packages: torchaudio
Successfully installed torchaudio-0.8.0
```
- Checking torchaudio :

```
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/discort/projects/.env/lib/python3.6/site-packages/torchaudio/__init__.py", line 1, in <module>
    from . import extension  # noqa: F401
  File "/home/discort/projects/.env/lib/python3.6/site-packages/torchaudio/extension/__init__.py", line 5, in <module>
    _init_extension()
  File "/home/discort/projects/.env/lib/python3.6/site-packages/torchaudio/extension/extension.py", line 11, in _init_extension
    _init_script_module(ext)
  File "/home/discort/projects/.env/lib/python3.6/site-packages/torchaudio/extension/extension.py", line 18, in _init_script_module
    torch.classes.load_library(path)
  File "/home/discort/projects/.env/lib/python3.6/site-packages/torch/_classes.py", line 46, in load_library
    torch.ops.load_library(path)
  File "/home/discort/projects/.env/lib/python3.6/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/discort/projects/.env/lib/python3.6/site-packages/torchaudio/_torchaudio.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```

## Environment
- python3.6
- nvidia-jetpack, Version: 4.4-b186

**Comment by KumaTea** [comment]
Hi.

It is most likely because that `torchaudio` v0.8.0 in this repo is compiled with [official `manylinux2014` wheels](https://pypi.org/project/torch/1.8.0/#files).

For some reason wheels built in this way can not be used if the fundamental `torch` packages differs. **You might need to compile it from source.**

P.S.: A possible attempt is also building manylinux wheels. But I've tried and found them contained the whole original `torch` libraries, which make the size extremely large. So I didn't continue to build them.

**Comment by discort** [comment]
Thanks for the quick update.

I'm experiencing `kaldi` issue on building from source:
```
CMake Error: CMake can not determine linker language for target: kaldi
```

But it's another topic of discussion. Will raise it on https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-8-0-now-available
